In [39]:
import pandas as pd
import pandasql as psql
from konlpy.tag import Okt
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.models import Word2Vec

In [28]:
# 조회수 테이블 불러오기

view = pd.read_csv('view_result.csv')
view.head()

                                      title  views             date
0                            신변보호사 자격증 알아보자   1154  2024.12.09. (월)
1           경비원 취업 신임경비교육 시험 난이도와 이수증 발급 방법    697  2025.09.30. (화)
2  국가공인 신변보호사 자격증 정보 총정리 (시험 일정, 접수처, 준비 팁)    586  2025.07.22. (화)
3                  ITQ 엑셀 자격증 시험 일정 및 합격 전략    411  2025.03.13. (목)
4                   민간자격증 취업 이력서에 작성해도 될까요?    374  2024.12.12. (목)

In [29]:
# 공감수 테이블 불러오기

empathy = pd.read_csv('empathy_result.csv')
empathy.head()

                                       title  empathies             date
0  중소기업 직무 교육비 지원 제도 기업직업훈련카드 기직카 신청 및 활용 방법         20  2025.06.18. (수)
1            경비원 취업 신임경비교육 시험 난이도와 이수증 발급 방법         19  2025.09.30. (화)
2      AID 30+ 집중캠프란? 2025년 선정 대학과 교육 분야 총정리         19  2025.11.06. (목)
3      전국 10개 미술대학, 디지털 배지로 신진 작가의 커리어를 증명하다         17  2025.08.22. (금)
4   국가공인 신변보호사 자격증 정보 총정리 (시험 일정, 접수처, 준비 팁)         16  2025.07.22. (화)

In [30]:
# SQL을 활용해서 두 개의 테이블 합치기

query = 'SELECT v.title, v.views, IFNULL(e.empathies, 0) AS empathies, v.date ' \
'FROM view v LEFT JOIN empathy e ON v.title = e.title'
result = psql.sqldf(query, locals())
result

,title,views,empathies,date
0,신변보호사 자격증 알아보자,1154,4,2024.12.09. (월)
1,경비원 취업 신임경비교육 시험 난이도와 이수증 발급 방법,697,19,2025.09.30. (화)
2,"국가공인 신변보호사 자격증 정보 총정리 (시험 일정, 접수처, 준비 팁)",586,16,2025.07.22. (화)
3,ITQ 엑셀 자격증 시험 일정 및 합격 전략,411,4,2025.03.13. (목)
4,민간자격증 취업 이력서에 작성해도 될까요?,374,1,2024.12.12. (목)
5,일본어 자격증 비교 FLEX JLPT JPT,370,1,2024.12.16. (월)
6,내일배움카드 발급 방법 및 취업에 유리한 국비지원 자격증 종류,347,11,2025.07.01. (화)
7,직무기술서 예시로 제대로 이해하기 합격률 높이는 방법,259,6,2025.04.17. (목)
8,직무기술서 예시 이렇게 쓰면 HR담당자 눈에 띕니다,246,14,2025.07.14. (월)
9,ITQ자격증 정보 유효기간 시험일정 과목 정리,214,13,2025.07.29. (화)
10,DELE FLEX 시험 스페인어 자격증 알아보기,209,2,2024.12.16. (월)
11,경력기술서 작성방법 이렇게 쓰면 면접까지 한 번에!,197,7,2025.05.22. (목)
12,애견미용사 자격증 따는 법 연봉까지 공개!,170,0,2024.12.16. (월)
13,병원행정사 자격증 취득 자격조건 및 평가내용 총정리,167,1,2024.12.09. (월)
14,교육디지털원패스 가입 방법과 회원가입 꿀팁,167,14,2025.08.28. (목)
15,네트워크 관리사 하는 일 취업 및 활동분야는 어디?,139,1,2024.12.16. (월)
16,국비지원 자격증 2025 국민내일배움카드 국비지원으로 자격증 도전,123,5,2025.03.17. (월)
17,식품위생교육 수료증 발급부터 신청·수강료까지 한 번에 확인하기,122,12,2025.08.13. (수)
18,kohi 의무교육 수료증 발급 가이드 보건복지 종사자 필수!,120,16,2025.08.26. (화)
19,공연장 안전교육 수료증 신청·이수 절차 발급까지,116,12,2025.09.16. (화)
20,자소서 잘 쓰는법 완벽 정리! 마스터 자소서로 취업 준비 끝내기,113,4,2025.04.29. (화)
21,안전교육수료증 발급 방법부터 활용처까지 한 번에 알아보기,109,9,2025.08.11. (월)
22,탐정사자격증 취득하는 방법 응시자격 시험일정,101,1,2024.12.12. (목)
23,2025 미국대학순위 완전 정리! 상위 10개 대학 전략까지,92,11,2025.06.24. (화)
24,인기 민간자격증 TOP 5 나에게 맞는 자격증은?,85,1,2024.12.09. (월)
25,중소기업 직무 교육비 지원 제도 기업직업훈련카드 기직카 신청 및 활용 방법,82,20,2025.06.18. (수)
26,RISE(라이즈) 사업이란? 서울시 선정 대학 명단과 핵심 추진 방향 정리,79,7,2025.11.04. (화)
27,국내 대학의 마이크로디그리 운영 방식은 어떨까요?,73,15,2025.08.08. (금)
28,퇴사 전 체크리스트 이것만은 꼭 챙기자! 월급 더 받는 퇴사 꿀팁,63,5,2025.05.08. (목)
29,카카오테크 부트캠프 알아보기 – IT 인재로 성장하는 첫걸음,62,11,2025.09.12. (금)
30,취업과 커리어 성장에 도움 되는 직장인 자격증 추천,62,4,2025.02.28. (금)

In [31]:
result.to_csv('result.csv', encoding='utf-8-sig')

In [32]:
# 수동 크롤링으로 게시물 내용 긁어와서 새로운 열로 추가

top_result = pd.read_csv('result_text.csv', encoding='euc-kr').drop('Column1', axis=1)
top_result

,title,views,empathies,date,text
0,RISE(라이즈) 사업이란? 서울시 선정 대학 명단과 핵심 추진 방향 정리,79,7,2025.11.04. (화),최근 교육계에서는 \n\n지방자치단체 중심의 대학 지원 체계 전환이라는 \n\n새로...
1,경비원 취업 신임경비교육 시험 난이도와 이수증 발급 방법,697,19,2025.09.30. (화),"오늘은 경비원 취업을 준비하시는 분들이라면 \n\n반드시 거쳐야 하는 관문, \n\..."
2,공연장 안전교육 수료증 신청·이수 절차 발급까지,116,12,2025.09.16. (화),오늘은 공연 관련 업계 종사자라면 \n\n꼭 알아야 하는 공연장 안전교육에 대해 \...
3,카카오테크 부트캠프 알아보기 ? IT 인재로 성장하는 첫걸음,62,11,2025.09.12. (금),빠르게 변화하는 IT 환경 속에서 \n\n끊임없이 새로운 기술이 등장하고 있는데요....
4,교육디지털원패스 가입 방법과 회원가입 꿀팁,167,14,2025.08.28. (목),"온라인 교육 서비스가 일상화되면서 \n\n학생, 교사, 학부모 모두가 다양한 \n\..."
5,kohi 의무교육 수료증 발급 가이드 보건복지 종사자 필수!,120,16,2025.08.26. (화),보건복지 분야에서 일하시는 분들이라면 \n\n한 번쯤 들어보셨을 kohi 의무교육\...
6,식품위생교육 수료증 발급부터 신청·수강료까지 한 번에 확인하기,122,12,2025.08.13. (수),식품 관련 업종을 운영하고 계신다면 \n\n매년 찾아오는 식품위생교육 수료증\n\n...
7,안전교육수료증 발급 방법부터 활용처까지 한 번에 알아보기,109,9,2025.08.11. (월),?\n\n요즘은 단순히 현장에서\n\n일하기 위해서가 아니라\n\n?\n\n학교 수...
8,국내 대학의 마이크로디그리 운영 방식은 어떨까요?,73,15,2025.08.08. (금),"변하는 대학 교육, 마이크로디그리가 해답입니다.\n\n마이크로디그리(Microdeg..."
9,ITQ자격증 정보 유효기간 시험일정 과목 정리,214,13,2025.07.29. (화),"오늘은 취업 준비생, 사무직 전환을 \n\n고민 중인 분들 사이에서 꾸준히 관심을 ..."
10,"국가공인 신변보호사 자격증 정보 총정리 (시험 일정, 접수처, 준비 팁)",586,16,2025.07.22. (화),"최근 사회 전반에 걸쳐 스토킹, 보복 범죄 등 \n\n개인의 안전을 위협하는 사건이..."
11,직무기술서 예시 이렇게 쓰면 HR담당자 눈에 띕니다,246,14,2025.07.14. (월),?\n\n오늘은 구직을 준비하시는 분들이 꼭 알아두셔야 할 \n\n직무기술서 예시와...
12,내일배움카드 발급 방법 및 취업에 유리한 국비지원 자격증 종류,347,11,2025.07.01. (화),요즘 많은 분들이 취업 경쟁력을 높이기 위해 \n\n다양한 자격증을 준비하고 계신데...
13,2025 미국대학순위 완전 정리! 상위 10개 대학 전략까지,92,11,2025.06.24. (화),요즘 미국 대학 진학을 준비하시는 분들이 많이 검색하시는 \n\n키워드 중 하나가 ...
14,중소기업 직무 교육비 지원 제도 기업직업훈련카드 기직카 신청 및 활용 방법,82,20,2025.06.18. (수),오늘은 기업의 교육 담당자 및 인사담당자 분들께 교육비 부담 없이 \n\n재직자 직...
15,경력기술서 작성방법 이렇게 쓰면 면접까지 한 번에!,197,7,2025.05.22. (목),"안녕하세요, \n\n디지털 인증서/배지 발급 솔루션\n\n 칼리지스입니다! \n\n..."
16,퇴사 전 체크리스트 이것만은 꼭 챙기자! 월급 더 받는 퇴사 꿀팁,63,5,2025.05.08. (목),"?\n\n안녕하세요, \n\n디지털 인증서/배지 발급 솔루션 \n\n칼리지스입니다...."
17,자소서 잘 쓰는법 완벽 정리! 마스터 자소서로 취업 준비 끝내기,113,4,2025.04.29. (화),"?\n\n안녕하세요, \n\n디지털 인증서/배지 발급 솔루션 칼리지스입니다!\n\n..."
18,직무기술서 예시로 제대로 이해하기 합격률 높이는 방법,259,6,2025.04.17. (목),안녕하세요!\n\n디지털 인증서/배지 발급 솔루션\n\n 칼리지스입니다.\n\n?\...
19,국비지원 자격증 2025 국민내일배움카드 국비지원으로 자격증 도전,123,5,2025.03.17. (월),"안녕하세요 칼리지스입니다.\n\n?\n\n직장인 여러분, 안녕하세요! 오늘은 202..."
20,ITQ 엑셀 자격증 시험 일정 및 합격 전략,411,4,2025.03.13. (목),안녕하세요! 칼리지스입니다. \n\n?\n\n오늘은 취업 준비생이나 직장인들에게 유...
21,취업과 커리어 성장에 도움 되는 직장인 자격증 추천,62,4,2025.02.28. (금),안녕하세요! 칼리지스입니다.\n\n?\n\n직장인이라면 한 번쯤 고민해봤을 거예요....
22,일본어 자격증 비교 FLEX JLPT JPT,370,1,2024.12.16. (월),안녕하세요 칼리지스입니다!\n\n?\n\n오늘은 일본어를 공부하시는 분들이라면 한 ...
23,DELE FLEX 시험 스페인어 자격증 알아보기,209,2,2024.12.16. (월),안녕하세요 칼리지스입니다!\n\n오늘은 많은 분들이 관심을 갖고 있는 스페인어 자격...
24,애견미용사 자격증 따는 법 연봉까지 공개!,170,0,2024.12.16. (월),?\n\n안녕하세요 칼리지스입니다~!\n\n?\n\n반려동물을 사랑하고 그들의 건강...
25,네트워크 관리사 하는 일 취업 및 활동분야는 어디?,139,1,2024.12.16. (월),안녕하세요 칼리지스입니다.\n\n?\n\n오늘은 네트워크 관리사에 대해 알아보려고 ...
26,민간자격증 취업 이력서에 작성해도 될까요?,374,1,2024.12.12. (목),안녕하세요 칼리지스입니다!\n\n오늘은 많은 분들이 궁금해하시는 민간자격증에 대해 ...
27,탐정사자격증 취득하는 방법 응시자격 시험일정,101,1,2024.12.12. (목),안녕하세요 칼리지스입니다!\n\n?\n\n오늘은 탐정사 자격증에 대해 알아보려고 해...
28,신변보호사 자격증 알아보자,1154,4,2024.12.09. (월),안녕하세요 칼리지스입니다!\n\n?\n\n오늘은 우리 주변의 안전을 책임지는 특별한...
29,병원행정사 자격증 취득 자격조건 및 평가내용 총정리,167,1,2024.12.09. (월),안녕하세요 칼리지스입니다!\n\n오늘은 병원행정 분야로 진출하려는 분들이라면 꼭 알...
30,인기 민간자격증 TOP 5 나에게 맞는 자격증은?,85,1,2024.12.09. (월),안녕하세요 칼리지스입니다! \n\n최근에 자기 계발과 전문성 향상을 위해 많은 분들...

In [34]:
# text에서 명사 추출

okt = Okt()
top_result['nouns'] = top_result['text'].apply(lambda x: [w for w, t in okt.pos(str(x)) if t == 'Noun'])
top_result

,title,views,empathies,date,text,nouns
0,RISE(라이즈) 사업이란? 서울시 선정 대학 명단과 핵심 추진 방향 정리,79,7,2025.11.04. (화),최근 교육계에서는 \n\n지방자치단체 중심의 대학 지원 체계 전환이라는 \n\n새로...,"[최근, 교육, 지방자치단체, 중심, 대학, 지원, 체계, 전환, 흐름, 주목, 그..."
1,경비원 취업 신임경비교육 시험 난이도와 이수증 발급 방법,697,19,2025.09.30. (화),"오늘은 경비원 취업을 준비하시는 분들이라면 \n\n반드시 거쳐야 하는 관문, \n\...","[오늘, 경비원, 취업, 준비, 분, 반드시, 관문, 바로, 신임, 경비, 교육, ..."
2,공연장 안전교육 수료증 신청·이수 절차 발급까지,116,12,2025.09.16. (화),오늘은 공연 관련 업계 종사자라면 \n\n꼭 알아야 하는 공연장 안전교육에 대해 \...,"[오늘, 공연, 관련, 업계, 종사, 꼭, 공연장, 안전교육, 대해, 이야기, 해,..."
3,카카오테크 부트캠프 알아보기 ? IT 인재로 성장하는 첫걸음,62,11,2025.09.12. (금),빠르게 변화하는 IT 환경 속에서 \n\n끊임없이 새로운 기술이 등장하고 있는데요....,"[변화, 환경, 속, 기술, 등장, 인공, 지능, 클라우드, 풀, 스택, 개발, 앞..."
4,교육디지털원패스 가입 방법과 회원가입 꿀팁,167,14,2025.08.28. (목),"온라인 교육 서비스가 일상화되면서 \n\n학생, 교사, 학부모 모두가 다양한 \n\...","[온라인, 교육, 서비스, 일상, 학생, 교사, 학부모, 모두, 교육, 플랫폼, 사..."
5,kohi 의무교육 수료증 발급 가이드 보건복지 종사자 필수!,120,16,2025.08.26. (화),보건복지 분야에서 일하시는 분들이라면 \n\n한 번쯤 들어보셨을 kohi 의무교육\...,"[보건, 복지, 분야, 일, 분, 번, 의무교육, 올해, 제도, 분, 오늘, 이, ..."
6,식품위생교육 수료증 발급부터 신청·수강료까지 한 번에 확인하기,122,12,2025.08.13. (수),식품 관련 업종을 운영하고 계신다면 \n\n매년 찾아오는 식품위생교육 수료증\n\n...,"[식품, 관련, 업종, 운영, 매년, 식품위생, 교육, 수료증, 발급, 시기, 거,..."
7,안전교육수료증 발급 방법부터 활용처까지 한 번에 알아보기,109,9,2025.08.11. (월),?\n\n요즘은 단순히 현장에서\n\n일하기 위해서가 아니라\n\n?\n\n학교 수...,"[요즘, 현장, 일, 위, 학교, 수업, 공공기관, 근무, 자격증, 응시, 등, 상..."
8,국내 대학의 마이크로디그리 운영 방식은 어떨까요?,73,15,2025.08.08. (금),"변하는 대학 교육, 마이크로디그리가 해답입니다.\n\n마이크로디그리(Microdeg...","[대학, 교육, 마이크로, 디그, 리가, 해답, 마이크로, 디그, 리, 소규모, 학..."
9,ITQ자격증 정보 유효기간 시험일정 과목 정리,214,13,2025.07.29. (화),"오늘은 취업 준비생, 사무직 전환을 \n\n고민 중인 분들 사이에서 꾸준히 관심을 ...","[오늘, 취업, 준비, 생, 사무직, 전환, 고민, 중인, 사이, 관심, 자격증, ..."
10,"국가공인 신변보호사 자격증 정보 총정리 (시험 일정, 접수처, 준비 팁)",586,16,2025.07.22. (화),"최근 사회 전반에 걸쳐 스토킹, 보복 범죄 등 \n\n개인의 안전을 위협하는 사건이...","[최근, 사회, 전반, 스토킹, 보복, 범죄, 등, 개인, 안전, 위협, 사건, 증..."
11,직무기술서 예시 이렇게 쓰면 HR담당자 눈에 띕니다,246,14,2025.07.14. (월),?\n\n오늘은 구직을 준비하시는 분들이 꼭 알아두셔야 할 \n\n직무기술서 예시와...,"[오늘, 구직, 준비, 분, 꼭, 알, 직무, 기술, 예시, 직무, 수행, 계획, ..."
12,내일배움카드 발급 방법 및 취업에 유리한 국비지원 자격증 종류,347,11,2025.07.01. (화),요즘 많은 분들이 취업 경쟁력을 높이기 위해 \n\n다양한 자격증을 준비하고 계신데...,"[요즘, 분, 취업, 경쟁력, 위해, 자격증, 준비, 정부, 지원, 배움, 카드, ..."
13,2025 미국대학순위 완전 정리! 상위 10개 대학 전략까지,92,11,2025.06.24. (화),요즘 미국 대학 진학을 준비하시는 분들이 많이 검색하시는 \n\n키워드 중 하나가 ...,"[요즘, 미국, 대학, 진학, 준비, 분, 검색, 키, 워드, 중, 하나, 바로, ..."
14,중소기업 직무 교육비 지원 제도 기업직업훈련카드 기직카 신청 및 활용 방법,82,20,2025.06.18. (수),오늘은 기업의 교육 담당자 및 인사담당자 분들께 교육비 부담 없이 \n\n재직자 직...,"[오늘, 기업, 교육, 담당자, 및, 인사, 담당자, 분, 교육비, 부담, 재직, ..."
15,경력기술서 작성방법 이렇게 쓰면 면접까지 한 번에!,197,7,2025.05.22. (목),"안녕하세요, \n\n디지털 인증서/배지 발급 솔루션\n\n 칼리지스입니다! \n\n...","[디지털, 인증서, 배지, 발급, 솔루션, 칼리, 지스, 오늘, 분, 경력, 기술,..."
16,퇴사 전 체크리스트 이것만은 꼭 챙기자! 월급 더 받는 퇴사 꿀팁,63,5,2025.05.08. (목),"?\n\n안녕하세요, \n\n디지털 인증서/배지 발급 솔루션 \n\n칼리지스입니다....","[디지털, 인증서, 배지, 발급, 솔루션, 칼리, 지스, 오늘, 이직, 커리어, 전..."
17,자소서 잘 쓰는법 완벽 정리! 마스터 자소서로 취업 준비 끝내기,113,4,2025.04.29. (화),"?\n\n안녕하세요, \n\n디지털 인증서/배지 발급 솔루션 칼리지스입니다!\n\n...","[디지털, 인증서, 배지, 발급, 솔루션, 칼리, 지스, 오늘, 채용, 트렌드, 꼭..."
18,직무기술서 예시로 제대로 이해하기 합격률 높이는 방법,259,6,2025.04.17. (목),안녕하세요!\n\n디지털 인증서/배지 발급 솔루션\n\n 칼리지스입니다.\n\n?\...,"[디지털, 인증서, 배지, 발급, 솔루션, 칼리, 지스, 오늘, 직무, 기술, 예시..."
19,국비지원 자격증 2025 국민내일배움카드 국비지원으로 자격증 도전,123,5,2025.03.17. (월),"안녕하세요 칼리지스입니다.\n\n?\n\n직장인 여러분, 안녕하세요! 오늘은 202...","[칼리, 지스, 직장인, 여러분, 오늘, 직장인, 꼭, 국비, 지원, 자격, 요건,..."
20,ITQ 엑셀 자격증 시험 일정 및 합격 전략,411,4,2025.03.13. (목),안녕하세요! 칼리지스입니다. \n\n?\n\n오늘은 취업 준비생이나 직장인들에게 유...,"[칼리, 지스, 오늘, 취업, 준비, 생, 직장인, 자격증, 엑셀, 자격증, 대해,..."
21,취업과 커리어 성장에 도움 되는 직장인 자격증 추천,62,4,2025.02.28. (금),안녕하세요! 칼리지스입니다.\n\n?\n\n직장인이라면 한 번쯤 고민해봤을 거예요....,"[칼리, 지스, 직장인, 라면, 번, 고민, 거, 더, 직장, 뭘, 이, 분야, 더..."
22,일본어 자격증 비교 FLEX JLPT JPT,370,1,2024.12.16. (월),안녕하세요 칼리지스입니다!\n\n?\n\n오늘은 일본어를 공부하시는 분들이라면 한 ...,"[칼리, 지스, 오늘, 일본어, 공부, 분, 번, 고민, 주제, 바로, 일본어, 자..."
23,DELE FLEX 시험 스페인어 자격증 알아보기,209,2,2024.12.16. (월),안녕하세요 칼리지스입니다!\n\n오늘은 많은 분들이 관심을 갖고 있는 스페인어 자격...,"[칼리, 지스, 오늘, 분, 관심, 스페인어, 자격증, 대해, 이야기, 해, 요즘,..."
24,애견미용사 자격증 따는 법 연봉까지 공개!,170,0,2024.12.16. (월),?\n\n안녕하세요 칼리지스입니다~!\n\n?\n\n반려동물을 사랑하고 그들의 건강...,"[칼리, 지스, 반려동물, 사랑, 그, 건강, 움, 위해, 헌신, 직업, 애견미용사..."
25,네트워크 관리사 하는 일 취업 및 활동분야는 어디?,139,1,2024.12.16. (월),안녕하세요 칼리지스입니다.\n\n?\n\n오늘은 네트워크 관리사에 대해 알아보려고 ...,"[칼리, 지스, 오늘, 네트워크, 관리사, 대해, 네트워크, 관리사, 기업, 조직,..."
26,민간자격증 취업 이력서에 작성해도 될까요?,374,1,2024.12.12. (목),안녕하세요 칼리지스입니다!\n\n오늘은 많은 분들이 궁금해하시는 민간자격증에 대해 ...,"[칼리, 지스, 오늘, 분, 민간, 자격증, 대해, 이야기, 해, 민간, 자격증, ..."
27,탐정사자격증 취득하는 방법 응시자격 시험일정,101,1,2024.12.12. (목),안녕하세요 칼리지스입니다!\n\n?\n\n오늘은 탐정사 자격증에 대해 알아보려고 해...,"[칼리, 지스, 오늘, 탐정, 사, 자격증, 대해, 해, 분, 탐정, 사라, 직업,..."
28,신변보호사 자격증 알아보자,1154,4,2024.12.09. (월),안녕하세요 칼리지스입니다!\n\n?\n\n오늘은 우리 주변의 안전을 책임지는 특별한...,"[칼리, 지스, 오늘, 우리, 주변, 안전, 자격증, 신변, 보호, 사, 자격증, ..."
29,병원행정사 자격증 취득 자격조건 및 평가내용 총정리,167,1,2024.12.09. (월),안녕하세요 칼리지스입니다!\n\n오늘은 병원행정 분야로 진출하려는 분들이라면 꼭 알...,"[칼리, 지스, 오늘, 병원, 행정, 분야, 진출, 분, 꼭, 병원, 행정사, 자격..."
30,인기 민간자격증 TOP 5 나에게 맞는 자격증은?,85,1,2024.12.09. (월),안녕하세요 칼리지스입니다! \n\n최근에 자기 계발과 전문성 향상을 위해 많은 분들...,"[칼리, 지스, 최근, 자기, 계발, 전문성, 향상, 위해, 분, 민간, 자격증, ..."

In [37]:
# 추출한 명사의 TF-IDF 계산

corpus = [' '.join(tokens) for tokens in top_result['nouns']]
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(corpus)
tfidf_scores = tfidf_matrix.mean(axis=0).A1
keywords = pd.DataFrame({
    'keyword' : vectorizer.get_feature_names_out(),
    'score' : tfidf_scores
}).sort_values('score', ascending=False).head(30)

print('인기 키워드 Top 30: ')
keywords

인기 키워드 Top 30:

     keyword     score
1126     자격증  0.122784
166       교육  0.083955
801       시험  0.073977
1359      직무  0.054320
237       기술  0.041854
743      수료증  0.039583
140       과정  0.039229
332       대학  0.038837
497       발급  0.035219
566       보호  0.035032
1308      준비  0.033379
1455      카드  0.033189
1349      지원  0.033029
1656      활용  0.032710
810       신변  0.031205
482       민간  0.030856
224       기관  0.030736
1450      취득  0.030256
900       엑셀  0.030140
1451      취업  0.028860
83        경험  0.028512
239       기업  0.028433
858     안전교육  0.026758
68        경력  0.026686
286       능력  0.025884
270     네트워크  0.025812
1140      자소  0.025690
71        경비  0.025634
543       병원  0.025577
1187      전공  0.025087

In [41]:
# word2vec 모델 학습

model = Word2Vec(sentences=top_result['nouns'], 
                 vector_size=100, 
                 window=5, 
                 min_count=2, 
                 sg=1)

In [45]:
# TF-IDF 상위 30개 키워드별 유사 단어 top 5 추출

top_keywords = keywords['keyword'].head(30).tolist()
recommendations = []
for kw in top_keywords:
    try:
        similar_words = [w for w, sim in model.wv.most_similar(kw, topn=8)]
        recommendations.append({
            '핵심키워드' : kw,
            '연관키워드' : ', '.join(similar_words),
        })
    except KeyError:
        continue

recommend_df = pd.DataFrame(recommendations)
recommend_df

   핵심키워드                                연관키워드
0    자격증        민간, 엑셀, 취업, 취득, 분, 공신, 도전, 기회
1     교육      과정, 기관, 온라인, 제공, 강의, 다음, 이수, 모두
2     시험       일정, 응시, 주관, 평가, 접수, 실기, 기능, 탐정
3     직무        예시, 계획, 기술, 수행, 를, 구조, 작성, 대한
4     기술        계획, 수행, 를, 예시, 성법, 구조, 직무, 경험
5    수료증  발급, 안전교육, 공연장, 절차, 식품위생, 이수, 과정, 교육
6     과정     근무, 식품위생, 후, 다음, 아래, 근로자, 교육, 영업
7     대학       혁신, 사업, 변화, 서울, 기반, 핵심, 학생, 순위
8     발급       수료증, 후, 절차, 수강, 신청, 교육, 기관, 과정
9     보호      사, 신변, 국가, 주목, 자격증, 경호, 안전, 이야기
10    준비      내용, 도전, 이력서, 공부, 필수, 오늘, 대해, 본인
11    카드      국민, 배움, 직업, 훈련, 제도, 지원, 국비, 직장인
12    지원   국민, 제도, 부담, 직장인, 국비, 고용노동부, 요, 리스트
13    활용       기회, 줄, 주요, 필요, 더욱, 기획, 환경, 전문성
14    신변       사, 보호, 일정, 자격증, 주목, 국가, 중인, 안전
15    민간   커리어, 이력서, 취업, 우선, 관심, 취득, 스페인어, 정말
16    기관    온라인, 오프라인, 이제, 통합, 교육, 수료, 경우, 집중
17    취득     스페인어, 컴퓨터, 권, 본인, 이력서, 의, 단계, 우선
18    엑셀     취득, 응시, 스페인어, 본인, 자격증, 의, 주관, 관련
19    취업     도전, 고민, 고려, 기회, 우선, 증명, 공신, 바리스타
20    경험       구성, 입사, 구체, 먼저, 상황, 문서, 가치, 강조
21    기업     직업, 개발, 비, 훈련, 실질, 최신, 경제, 고용노동부
22  안전교육   공연장, 수료증, 발급, 이수, 절차, 센터, 과정, 식품위생
23    경력         그, 게, 작성, 만약, 실행, 만큼, 구체, 변화
24    능력        최신, 실제, 때, 자기, 또한, 위해, 제출, 환경
25  네트워크     관리사, 관리, 클라우드, 보안, 일, 요즘, 능력, 조직
26    자소        법, 마스터, 작성, 대해, 단계, 부서, 걸, 소서
27    경비       신임, 기관, 한국, 탐정, 유효, 응시, 필기, 목적
28    병원        누구, 더, 로그인, 리스트, 만약, 곳, 직, 부서
29    전공     추천, 위치, 포인트, 전략, 활동, 수학, 서울시, 학교